name: Technical Improvement
description: Track technical debt, maintenance, or internal improvements
labels: ["type:technical"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - build
        - performance
        - accessibility
        - security
        - seo
        - quality
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be improved and why?
      placeholder: Describe the technical improvement...
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Specific items to complete (use checkboxes)
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: Related issues, PRs, documentation, or external resources
      placeholder: "#5, https://..."
    validations:
      required: false
